-- 코드를 작성해주세요

SELECT ED3.ID
  FROM ECOLI_DATA AS ED3
  WHERE ED3.PARENT_ID IN (
    SELECT ED2.ID
      FROM ECOLI_DATA AS ED2
      WHERE ED2.PARENT_ID IN (
        SELECT ED.ID
          FROM ECOLI_DATA AS ED
          WHERE ED.PARENT_ID IS NULL
      )
  )
ORDER BY ID;