-- 코드를 입력하세요
WITH CAR AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR AS C
     WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT *
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
         WHERE C.CAR_ID = CH.CAR_ID
           AND CH.START_DATE <= '2022-11-30'
           AND CH.END_DATE >= '2022-11-01'
    )
)

SELECT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR(CAR.DAILY_FEE * 30 * (1 - CD.DISCOUNT_RATE / 100)) AS FEE
  FROM CAR JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CD
    ON CAR.CAR_TYPE = CD.CAR_TYPE
 WHERE CD.DURATION_TYPE = '30일 이상'
   AND FLOOR(CAR.DAILY_FEE * 30 * (1 - CD.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;
    