-- 코드를 작성해주세요
SELECT COUNT(F.ID) AS FISH_COUNT, FN.FISH_NAME
  FROM FISH_INFO AS F JOIN FISH_NAME_INFO AS FN
    ON F.FISH_TYPE = FN.FISH_TYPE
GROUP BY F.FISH_TYPE, FN.FISH_NAME
ORDER BY FISH_COUNT DESC;