-- 코드를 작성해주세요

# 각 분기 별로 정리된 항목 출력
# SELECT QUARTER, (
#   # 대장균의 숫자 카운트     
#   SELECT COUNT(*) AS ECOLI_COUNT
#   FROM ECOLI_DATA
#   GROUP BY DIFFRENTIATION_DATE
# )
#   FROM ECOLI_DATA
 
SELECT CONCAT(QUARTER(DIFFERENTIATION_DATE), "Q") AS QUARTER, COUNT(*) AS ECOLI_COUNT
  FROM ECOLI_DATA
  GROUP BY QUARTER
  ORDER BY QUARTER;


