-- 코드를 작성해주세요
WITH FRONTEND AS (
    SELECT NAME, CATEGORY, CODE
      FROM SKILLCODES
     WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
  FROM DEVELOPERS D JOIN FRONTEND F
    ON (D.SKILL_CODE & F.CODE) != 0
ORDER BY D.ID;